Add confirmation
iTechArt-RubyLab/dress_rental pull request #4
Opened 2023-04-25 06:35 UTC by MariaGrechko

Features:
- add email confirmation letter
- after clicking the confirmation link the user is automatically signed in

2023-04-25 09:02 UTC, fooooxmr requested changes

2023-04-25 09:02 UTC, fooooxmr commented on app/controllers/users_controller.rb
> +        redirect_to root_path
It's not a good idea to use redirect_to insider respond_to method.
You need to left format.html in case of using respond_to and remove redirect_to

2023-04-25 09:03 UTC, fooooxmr commented on app/controllers/users_controller.rb
> +        redirect_to root_path
In your case, redirect_to always will be performed.

2023-04-25 11:29 UTC, MariaGrechko commented on app/controllers/users_controller.rb
> +        redirect_to root_path
Deleted that line, thanks c:

2023-04-26 11:56 UTC, fooooxmr approved these changes

2023-04-26 11:56 UTC, merged